# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SensorUI.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SensorInterface(object):
    def setupUi(self, SensorInterface):
        SensorInterface.setObjectName("SensorInterface")
        SensorInterface.resize(1127, 866)
        font = QtGui.QFont()
        font.setFamily("PibotoLt")
        SensorInterface.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/tempAvg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SensorInterface.setWindowIcon(icon)
        SensorInterface.setWindowOpacity(10.0)
        SensorInterface.setStyleSheet("background-color: rgb(24, 24, 24);\n"
"")
        self.refreshButton = QtWidgets.QPushButton(SensorInterface)
        self.refreshButton.setGeometry(QtCore.QRect(120, 760, 85, 85))
        self.refreshButton.setStyleSheet("")
        self.refreshButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Images/refreshbutton.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refreshButton.setIcon(icon1)
        self.refreshButton.setIconSize(QtCore.QSize(70, 70))
        self.refreshButton.setDefault(False)
        self.refreshButton.setFlat(True)
        self.refreshButton.setObjectName("refreshButton")
        self.exitButton = QtWidgets.QPushButton(SensorInterface)
        self.exitButton.setGeometry(QtCore.QRect(920, 760, 85, 85))
        self.exitButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Images/powerbutton.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitButton.setIcon(icon2)
        self.exitButton.setIconSize(QtCore.QSize(80, 80))
        self.exitButton.setAutoDefault(False)
        self.exitButton.setFlat(True)
        self.exitButton.setObjectName("exitButton")
        self.temperatureLabel = QtWidgets.QLabel(SensorInterface)
        self.temperatureLabel.setGeometry(QtCore.QRect(105, 60, 121, 131))
        self.temperatureLabel.setText("")
        self.temperatureLabel.setPixmap(QtGui.QPixmap("Images/temperature.png"))
        self.temperatureLabel.setObjectName("temperatureLabel")
        self.humidityLabel = QtWidgets.QLabel(SensorInterface)
        self.humidityLabel.setGeometry(QtCore.QRect(910, 60, 101, 131))
        self.humidityLabel.setText("")
        self.humidityLabel.setPixmap(QtGui.QPixmap("Images/humidity.png"))
        self.humidityLabel.setObjectName("humidityLabel")
        self.timeLabel = QtWidgets.QLabel(SensorInterface)
        self.timeLabel.setGeometry(QtCore.QRect(525, 10, 91, 91))
        self.timeLabel.setText("")
        self.timeLabel.setPixmap(QtGui.QPixmap("Images/clock.png"))
        self.timeLabel.setObjectName("timeLabel")
        self.timeDisplay = QtWidgets.QLineEdit(SensorInterface)
        self.timeDisplay.setGeometry(QtCore.QRect(490, 110, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.timeDisplay.setFont(font)
        self.timeDisplay.setStyleSheet("color: rgb(255, 255, 255);")
        self.timeDisplay.setObjectName("timeDisplay")
        self.alertDisplay = QtWidgets.QLineEdit(SensorInterface)
        self.alertDisplay.setGeometry(QtCore.QRect(440, 340, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.alertDisplay.setFont(font)
        self.alertDisplay.setAutoFillBackground(False)
        self.alertDisplay.setStyleSheet("color: rgb(255, 255, 255);")
        self.alertDisplay.setObjectName("alertDisplay")
        self.alertLabel = QtWidgets.QLabel(SensorInterface)
        self.alertLabel.setGeometry(QtCore.QRect(525, 240, 91, 91))
        self.alertLabel.setText("")
        self.alertLabel.setPixmap(QtGui.QPixmap("Images/alert.png"))
        self.alertLabel.setObjectName("alertLabel")
        self.temperatureDisplay = QtWidgets.QLCDNumber(SensorInterface)
        self.temperatureDisplay.setGeometry(QtCore.QRect(80, 200, 181, 81))
        self.temperatureDisplay.setStyleSheet("color: rgb(255, 255, 255);")
        self.temperatureDisplay.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.temperatureDisplay.setObjectName("temperatureDisplay")
        self.humidityDisplay = QtWidgets.QLCDNumber(SensorInterface)
        self.humidityDisplay.setGeometry(QtCore.QRect(870, 200, 181, 81))
        self.humidityDisplay.setStyleSheet("color: rgb(255, 255, 255);")
        self.humidityDisplay.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.humidityDisplay.setObjectName("humidityDisplay")
        self.celciusButton = QtWidgets.QPushButton(SensorInterface)
        self.celciusButton.setGeometry(QtCore.QRect(48, 200, 31, 31))
        self.celciusButton.setStyleSheet("color: rgb(0, 0, 0);")
        self.celciusButton.setObjectName("celciusButton")
        self.fahrenheitButton = QtWidgets.QPushButton(SensorInterface)
        self.fahrenheitButton.setGeometry(QtCore.QRect(48, 250, 31, 31))
        self.fahrenheitButton.setStyleSheet("color: rgb(0, 0, 0);")
        self.fahrenheitButton.setObjectName("fahrenheitButton")
        self.timerButton = QtWidgets.QPushButton(SensorInterface)
        self.timerButton.setGeometry(QtCore.QRect(530, 760, 85, 85))
        self.timerButton.setStyleSheet("")
        self.timerButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Images/timerbutton.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.timerButton.setIcon(icon3)
        self.timerButton.setIconSize(QtCore.QSize(80, 80))
        self.timerButton.setFlat(True)
        self.timerButton.setObjectName("timerButton")
        self.temperatureAvgLabel = QtWidgets.QLabel(SensorInterface)
        self.temperatureAvgLabel.setGeometry(QtCore.QRect(120, 385, 51, 61))
        self.temperatureAvgLabel.setText("")
        self.temperatureAvgLabel.setPixmap(QtGui.QPixmap("Images/tempAvg.png"))
        self.temperatureAvgLabel.setObjectName("temperatureAvgLabel")
        self.avgLabel1 = QtWidgets.QLabel(SensorInterface)
        self.avgLabel1.setGeometry(QtCore.QRect(170, 385, 31, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.avgLabel1.setFont(font)
        self.avgLabel1.setStyleSheet("color: rgb(255, 255, 255);")
        self.avgLabel1.setObjectName("avgLabel1")
        self.humidityAvgLabel = QtWidgets.QLabel(SensorInterface)
        self.humidityAvgLabel.setGeometry(QtCore.QRect(920, 390, 51, 61))
        self.humidityAvgLabel.setText("")
        self.humidityAvgLabel.setPixmap(QtGui.QPixmap("Images/humidityAvg.png"))
        self.humidityAvgLabel.setObjectName("humidityAvgLabel")
        self.avgLabel2 = QtWidgets.QLabel(SensorInterface)
        self.avgLabel2.setGeometry(QtCore.QRect(970, 390, 31, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.avgLabel2.setFont(font)
        self.avgLabel2.setStyleSheet("color: rgb(255, 255, 255);")
        self.avgLabel2.setObjectName("avgLabel2")
        self.temperatureAvgDisplay = QtWidgets.QLCDNumber(SensorInterface)
        self.temperatureAvgDisplay.setGeometry(QtCore.QRect(110, 450, 101, 51))
        self.temperatureAvgDisplay.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);")
        self.temperatureAvgDisplay.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.temperatureAvgDisplay.setObjectName("temperatureAvgDisplay")
        self.humidityAvgDisplay = QtWidgets.QLCDNumber(SensorInterface)
        self.humidityAvgDisplay.setGeometry(QtCore.QRect(910, 450, 101, 51))
        self.humidityAvgDisplay.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);")
        self.humidityAvgDisplay.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.humidityAvgDisplay.setObjectName("humidityAvgDisplay")
        self.resetButton = QtWidgets.QPushButton(SensorInterface)
        self.resetButton.setGeometry(QtCore.QRect(80, 450, 21, 21))
        self.resetButton.setStyleSheet("color: rgb(0, 0, 0);")
        self.resetButton.setObjectName("resetButton")
        self.tempDial = QtWidgets.QDial(SensorInterface)
        self.tempDial.setGeometry(QtCore.QRect(80, 300, 61, 61))
        self.tempDial.setMinimum(-15)
        self.tempDial.setMaximum(45)
        self.tempDial.setSingleStep(1)
        self.tempDial.setProperty("value", -15)
        self.tempDial.setTracking(False)
        self.tempDial.setOrientation(QtCore.Qt.Horizontal)
        self.tempDial.setObjectName("tempDial")
        self.humDial = QtWidgets.QDial(SensorInterface)
        self.humDial.setGeometry(QtCore.QRect(880, 300, 61, 61))
        self.humDial.setMinimum(10)
        self.humDial.setMaximum(80)
        self.humDial.setProperty("value", 10)
        self.humDial.setTracking(False)
        self.humDial.setObjectName("humDial")
        self.tempThresholdDisplay = QtWidgets.QLCDNumber(SensorInterface)
        self.tempThresholdDisplay.setGeometry(QtCore.QRect(150, 315, 61, 31))
        self.tempThresholdDisplay.setStyleSheet("color: rgb(255, 255, 255);")
        self.tempThresholdDisplay.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tempThresholdDisplay.setDigitCount(3)
        self.tempThresholdDisplay.setObjectName("tempThresholdDisplay")
        self.humThresholdDisplay = QtWidgets.QLCDNumber(SensorInterface)
        self.humThresholdDisplay.setGeometry(QtCore.QRect(950, 315, 61, 31))
        self.humThresholdDisplay.setStyleSheet("color: rgb(255, 255, 255);")
        self.humThresholdDisplay.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.humThresholdDisplay.setDigitCount(3)
        self.humThresholdDisplay.setObjectName("humThresholdDisplay")
        self.tempThresholdLabel = QtWidgets.QLabel(SensorInterface)
        self.tempThresholdLabel.setGeometry(QtCore.QRect(220, 320, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.tempThresholdLabel.setFont(font)
        self.tempThresholdLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.tempThresholdLabel.setObjectName("tempThresholdLabel")
        self.humThresholdLabel = QtWidgets.QLabel(SensorInterface)
        self.humThresholdLabel.setGeometry(QtCore.QRect(1020, 320, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.humThresholdLabel.setFont(font)
        self.humThresholdLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.humThresholdLabel.setObjectName("humThresholdLabel")
        self.timerStatus = QtWidgets.QLineEdit(SensorInterface)
        self.timerStatus.setGeometry(QtCore.QRect(615, 760, 16, 16))
        self.timerStatus.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.timerStatus.setObjectName("timerStatus")
        self.sensorStatus = QtWidgets.QLineEdit(SensorInterface)
        self.sensorStatus.setGeometry(QtCore.QRect(560, 180, 21, 21))
        self.sensorStatus.setAutoFillBackground(False)
        self.sensorStatus.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.sensorStatus.setObjectName("sensorStatus")
        self.highlabel1 = QtWidgets.QLabel(SensorInterface)
        self.highlabel1.setGeometry(QtCore.QRect(100, 540, 41, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.highlabel1.setFont(font)
        self.highlabel1.setStyleSheet("color: rgb(255, 255, 255);")
        self.highlabel1.setObjectName("highlabel1")
        self.temperatureHighDisplay = QtWidgets.QLCDNumber(SensorInterface)
        self.temperatureHighDisplay.setGeometry(QtCore.QRect(40, 605, 101, 51))
        self.temperatureHighDisplay.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);")
        self.temperatureHighDisplay.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.temperatureHighDisplay.setObjectName("temperatureHighDisplay")
        self.temperatureHighLabel = QtWidgets.QLabel(SensorInterface)
        self.temperatureHighLabel.setGeometry(QtCore.QRect(50, 540, 51, 61))
        self.temperatureHighLabel.setText("")
        self.temperatureHighLabel.setPixmap(QtGui.QPixmap("Images/tempAvg.png"))
        self.temperatureHighLabel.setObjectName("temperatureHighLabel")
        self.lowlabel1 = QtWidgets.QLabel(SensorInterface)
        self.lowlabel1.setGeometry(QtCore.QRect(250, 540, 41, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lowlabel1.setFont(font)
        self.lowlabel1.setStyleSheet("color: rgb(255, 255, 255);")
        self.lowlabel1.setObjectName("lowlabel1")
        self.temperatureLowDisplay = QtWidgets.QLCDNumber(SensorInterface)
        self.temperatureLowDisplay.setGeometry(QtCore.QRect(190, 605, 101, 51))
        self.temperatureLowDisplay.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);")
        self.temperatureLowDisplay.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.temperatureLowDisplay.setObjectName("temperatureLowDisplay")
        self.temperatureLowLabel = QtWidgets.QLabel(SensorInterface)
        self.temperatureLowLabel.setGeometry(QtCore.QRect(200, 540, 51, 61))
        self.temperatureLowLabel.setText("")
        self.temperatureLowLabel.setPixmap(QtGui.QPixmap("Images/tempAvg.png"))
        self.temperatureLowLabel.setObjectName("temperatureLowLabel")
        self.humidityHighDisplay = QtWidgets.QLCDNumber(SensorInterface)
        self.humidityHighDisplay.setGeometry(QtCore.QRect(830, 605, 101, 51))
        self.humidityHighDisplay.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);")
        self.humidityHighDisplay.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.humidityHighDisplay.setObjectName("humidityHighDisplay")
        self.highlabel2 = QtWidgets.QLabel(SensorInterface)
        self.highlabel2.setGeometry(QtCore.QRect(890, 540, 41, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.highlabel2.setFont(font)
        self.highlabel2.setStyleSheet("color: rgb(255, 255, 255);")
        self.highlabel2.setObjectName("highlabel2")
        self.humidityHighLabel = QtWidgets.QLabel(SensorInterface)
        self.humidityHighLabel.setGeometry(QtCore.QRect(840, 540, 51, 61))
        self.humidityHighLabel.setText("")
        self.humidityHighLabel.setPixmap(QtGui.QPixmap("Images/humidityAvg.png"))
        self.humidityHighLabel.setObjectName("humidityHighLabel")
        self.humidityLowDisplay = QtWidgets.QLCDNumber(SensorInterface)
        self.humidityLowDisplay.setGeometry(QtCore.QRect(980, 605, 101, 51))
        self.humidityLowDisplay.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);")
        self.humidityLowDisplay.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.humidityLowDisplay.setObjectName("humidityLowDisplay")
        self.lowlabel2 = QtWidgets.QLabel(SensorInterface)
        self.lowlabel2.setGeometry(QtCore.QRect(1040, 540, 41, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lowlabel2.setFont(font)
        self.lowlabel2.setStyleSheet("color: rgb(255, 255, 255);")
        self.lowlabel2.setObjectName("lowlabel2")
        self.humidityLowLabel = QtWidgets.QLabel(SensorInterface)
        self.humidityLowLabel.setGeometry(QtCore.QRect(990, 540, 51, 61))
        self.humidityLowLabel.setText("")
        self.humidityLowLabel.setPixmap(QtGui.QPixmap("Images/humidityAvg.png"))
        self.humidityLowLabel.setObjectName("humidityLowLabel")
        self.cleardatabaseButton = QtWidgets.QPushButton(SensorInterface)
        self.cleardatabaseButton.setGeometry(QtCore.QRect(505, 410, 131, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cleardatabaseButton.setFont(font)
        self.cleardatabaseButton.setObjectName("cleardatabaseButton")
        self.graphButton = QtWidgets.QPushButton(SensorInterface)
        self.graphButton.setGeometry(QtCore.QRect(520, 590, 101, 81))
        self.graphButton.setAutoFillBackground(False)
        self.graphButton.setStyleSheet("color: rgb(0, 0, 0);")
        self.graphButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Images/graph.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.graphButton.setIcon(icon4)
        self.graphButton.setIconSize(QtCore.QSize(90, 90))
        self.graphButton.setFlat(True)
        self.graphButton.setObjectName("graphButton")

        self.retranslateUi(SensorInterface)
        self.exitButton.clicked.connect(SensorInterface.close)
        QtCore.QMetaObject.connectSlotsByName(SensorInterface)

    def retranslateUi(self, SensorInterface):
        _translate = QtCore.QCoreApplication.translate
        SensorInterface.setWindowTitle(_translate("SensorInterface", "Sensor Interface"))
        self.celciusButton.setText(_translate("SensorInterface", "C"))
        self.fahrenheitButton.setText(_translate("SensorInterface", "F"))
        self.avgLabel1.setText(_translate("SensorInterface", "AVG"))
        self.avgLabel2.setText(_translate("SensorInterface", "AVG"))
        self.resetButton.setText(_translate("SensorInterface", "R"))
        self.tempThresholdLabel.setText(_translate("SensorInterface", "TT"))
        self.humThresholdLabel.setText(_translate("SensorInterface", "HT"))
        self.highlabel1.setText(_translate("SensorInterface", "HIGH"))
        self.lowlabel1.setText(_translate("SensorInterface", "LOW"))
        self.highlabel2.setText(_translate("SensorInterface", "HIGH"))
        self.lowlabel2.setText(_translate("SensorInterface", "LOW"))
        self.cleardatabaseButton.setText(_translate("SensorInterface", "Clear Database"))

