# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Project1.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 470)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setBold(True)
        font.setWeight(75)
        Form.setFont(font)
        Form.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.get_hum = QtWidgets.QPushButton(Form)
        self.get_hum.setGeometry(QtCore.QRect(330, 250, 151, 38))
        self.get_hum.setObjectName("get_hum")
        self.hum_icon = QtWidgets.QLabel(Form)
        self.hum_icon.setGeometry(QtCore.QRect(20, 220, 81, 101))
        self.hum_icon.setText("")
        self.hum_icon.setPixmap(QtGui.QPixmap("../../eid-fall2018/Project 1/My_Application/humidity-icon-weather-sensor-label-260nw-501091582.jpg"))
        self.hum_icon.setScaledContents(True)
        self.hum_icon.setObjectName("hum_icon")
        self.get_temp = QtWidgets.QPushButton(Form)
        self.get_temp.setGeometry(QtCore.QRect(340, 73, 129, 38))
        self.get_temp.setObjectName("get_temp")
        self.TOR = QtWidgets.QLabel(Form)
        self.TOR.setGeometry(QtCore.QRect(520, 10, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.TOR.setFont(font)
        self.TOR.setObjectName("TOR")
        self.temp_icon = QtWidgets.QLabel(Form)
        self.temp_icon.setGeometry(QtCore.QRect(20, 43, 71, 91))
        self.temp_icon.setText("")
        self.temp_icon.setPixmap(QtGui.QPixmap("../../eid-fall2018/Project 1/My_Application/thermometer-measure-temperature-icon-vector-14208472.jpg"))
        self.temp_icon.setScaledContents(True)
        self.temp_icon.setObjectName("temp_icon")
        self.refresh = QtWidgets.QPushButton(Form)
        self.refresh.setGeometry(QtCore.QRect(350, 340, 111, 91))
        self.refresh.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../eid-fall2018/Project 1/Icon/unnamed.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refresh.setIcon(icon)
        self.refresh.setIconSize(QtCore.QSize(101, 71))
        self.refresh.setObjectName("refresh")
        self.temp = QtWidgets.QLCDNumber(Form)
        self.temp.setEnabled(True)
        self.temp.setGeometry(QtCore.QRect(110, 43, 141, 101))
        self.temp.setSmallDecimalPoint(True)
        self.temp.setDigitCount(4)
        self.temp.setObjectName("temp")
        self.hum = QtWidgets.QLCDNumber(Form)
        self.hum.setGeometry(QtCore.QRect(110, 220, 141, 101))
        self.hum.setSmallDecimalPoint(True)
        self.hum.setDigitCount(4)
        self.hum.setProperty("intValue", 0)
        self.hum.setObjectName("hum")
        self.temp_TOR = QtWidgets.QLCDNumber(Form)
        self.temp_TOR.setGeometry(QtCore.QRect(503, 65, 181, 61))
        self.temp_TOR.setSmallDecimalPoint(False)
        self.temp_TOR.setDigitCount(8)
        self.temp_TOR.setObjectName("temp_TOR")
        self.hum_TOR = QtWidgets.QLCDNumber(Form)
        self.hum_TOR.setGeometry(QtCore.QRect(500, 240, 181, 61))
        self.hum_TOR.setSmallDecimalPoint(False)
        self.hum_TOR.setDigitCount(8)
        self.hum_TOR.setObjectName("hum_TOR")
        self.exit = QtWidgets.QPushButton(Form)
        self.exit.setGeometry(QtCore.QRect(540, 370, 129, 38))
        self.exit.setObjectName("exit")
        self.threshold_button = QtWidgets.QPushButton(Form)
        self.threshold_button.setGeometry(QtCore.QRect(10, 350, 281, 71))
        self.threshold_button.setObjectName("threshold_button")
        self.degree_button = QtWidgets.QPushButton(Form)
        self.degree_button.setGeometry(QtCore.QRect(260, 43, 61, 51))
        self.degree_button.setObjectName("degree_button")
        self.fahrenheit_button = QtWidgets.QPushButton(Form)
        self.fahrenheit_button.setGeometry(QtCore.QRect(260, 93, 61, 51))
        self.fahrenheit_button.setObjectName("fahrenheit_button")
        self.refresh_checkBox = QtWidgets.QCheckBox(Form)
        self.refresh_checkBox.setGeometry(QtCore.QRect(320, 430, 161, 33))
        self.refresh_checkBox.setObjectName("refresh_checkBox")
        self.TempAndHumidity = QtWidgets.QPushButton(Form)
        self.TempAndHumidity.setGeometry(QtCore.QRect(260, 170, 291, 38))
        self.TempAndHumidity.setObjectName("TempAndHumidity")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Environment Monitor"))
        self.get_hum.setText(_translate("Form", "Get Humidity"))
        self.get_temp.setText(_translate("Form", "Get Temp"))
        self.TOR.setText(_translate("Form", "Time of Request"))
        self.exit.setText(_translate("Form", "EXIT"))
        self.threshold_button.setText(_translate("Form", "SET TEMP THRESHOLD"))
        self.degree_button.setText(_translate("Form", "°C"))
        self.fahrenheit_button.setText(_translate("Form", "°F"))
        self.refresh_checkBox.setText(_translate("Form", "Auto Refresh"))
        self.TempAndHumidity.setText(_translate("Form", "Temp and Humidity"))

