# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Project1.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(827, 760)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setBold(True)
        font.setWeight(75)
        Form.setFont(font)
        Form.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.get_hum = QtWidgets.QPushButton(Form)
        self.get_hum.setGeometry(QtCore.QRect(360, 280, 151, 38))
        self.get_hum.setObjectName("get_hum")
        self.hum_icon = QtWidgets.QLabel(Form)
        self.hum_icon.setGeometry(QtCore.QRect(50, 250, 81, 101))
        self.hum_icon.setText("")
        self.hum_icon.setPixmap(QtGui.QPixmap("../../eid-fall2018/Project 1/My_Application/humidity-icon-weather-sensor-label-260nw-501091582.jpg"))
        self.hum_icon.setScaledContents(True)
        self.hum_icon.setObjectName("hum_icon")
        self.get_temp = QtWidgets.QPushButton(Form)
        self.get_temp.setGeometry(QtCore.QRect(370, 73, 129, 38))
        self.get_temp.setObjectName("get_temp")
        self.TOR = QtWidgets.QLabel(Form)
        self.TOR.setGeometry(QtCore.QRect(550, 10, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.TOR.setFont(font)
        self.TOR.setObjectName("TOR")
        self.temp_icon = QtWidgets.QLabel(Form)
        self.temp_icon.setGeometry(QtCore.QRect(50, 43, 71, 91))
        self.temp_icon.setText("")
        self.temp_icon.setPixmap(QtGui.QPixmap("../../eid-fall2018/Project 1/My_Application/thermometer-measure-temperature-icon-vector-14208472.jpg"))
        self.temp_icon.setScaledContents(True)
        self.temp_icon.setObjectName("temp_icon")
        self.refresh = QtWidgets.QPushButton(Form)
        self.refresh.setGeometry(QtCore.QRect(540, 570, 111, 91))
        self.refresh.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../eid-fall2018/Project 1/Icon/unnamed.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refresh.setIcon(icon)
        self.refresh.setIconSize(QtCore.QSize(101, 71))
        self.refresh.setObjectName("refresh")
        self.temp = QtWidgets.QLCDNumber(Form)
        self.temp.setEnabled(True)
        self.temp.setGeometry(QtCore.QRect(140, 43, 141, 101))
        self.temp.setSmallDecimalPoint(True)
        self.temp.setDigitCount(4)
        self.temp.setObjectName("temp")
        self.hum = QtWidgets.QLCDNumber(Form)
        self.hum.setGeometry(QtCore.QRect(140, 250, 141, 101))
        self.hum.setSmallDecimalPoint(True)
        self.hum.setDigitCount(4)
        self.hum.setProperty("intValue", 0)
        self.hum.setObjectName("hum")
        self.temp_TOR = QtWidgets.QLCDNumber(Form)
        self.temp_TOR.setGeometry(QtCore.QRect(533, 65, 181, 61))
        self.temp_TOR.setSmallDecimalPoint(False)
        self.temp_TOR.setDigitCount(8)
        self.temp_TOR.setObjectName("temp_TOR")
        self.hum_TOR = QtWidgets.QLCDNumber(Form)
        self.hum_TOR.setGeometry(QtCore.QRect(530, 270, 181, 61))
        self.hum_TOR.setSmallDecimalPoint(False)
        self.hum_TOR.setDigitCount(8)
        self.hum_TOR.setObjectName("hum_TOR")
        self.exit = QtWidgets.QPushButton(Form)
        self.exit.setGeometry(QtCore.QRect(370, 670, 129, 38))
        self.exit.setObjectName("exit")
        self.threshold_button = QtWidgets.QPushButton(Form)
        self.threshold_button.setGeometry(QtCore.QRect(40, 570, 251, 71))
        self.threshold_button.setObjectName("threshold_button")
        self.degree_button = QtWidgets.QPushButton(Form)
        self.degree_button.setGeometry(QtCore.QRect(290, 43, 61, 51))
        self.degree_button.setObjectName("degree_button")
        self.fahrenheit_button = QtWidgets.QPushButton(Form)
        self.fahrenheit_button.setGeometry(QtCore.QRect(290, 93, 61, 51))
        self.fahrenheit_button.setObjectName("fahrenheit_button")
        self.refresh_checkBox = QtWidgets.QCheckBox(Form)
        self.refresh_checkBox.setEnabled(False)
        self.refresh_checkBox.setGeometry(QtCore.QRect(580, 660, 161, 33))
        self.refresh_checkBox.setObjectName("refresh_checkBox")
        self.TempAndHumidity = QtWidgets.QPushButton(Form)
        self.TempAndHumidity.setGeometry(QtCore.QRect(290, 180, 291, 38))
        self.TempAndHumidity.setObjectName("TempAndHumidity")
        self.stop_refresh = QtWidgets.QPushButton(Form)
        self.stop_refresh.setGeometry(QtCore.QRect(680, 570, 111, 91))
        self.stop_refresh.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Icon/Stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop_refresh.setIcon(icon1)
        self.stop_refresh.setIconSize(QtCore.QSize(101, 71))
        self.stop_refresh.setObjectName("stop_refresh")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(140, 420, 221, 28))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(540, 420, 221, 28))
        self.label_2.setObjectName("label_2")
        self.tempAvg = QtWidgets.QLCDNumber(Form)
        self.tempAvg.setGeometry(QtCore.QRect(180, 450, 141, 101))
        self.tempAvg.setSmallDecimalPoint(True)
        self.tempAvg.setDigitCount(4)
        self.tempAvg.setProperty("intValue", 0)
        self.tempAvg.setObjectName("tempAvg")
        self.humAvg = QtWidgets.QLCDNumber(Form)
        self.humAvg.setGeometry(QtCore.QRect(560, 450, 141, 101))
        self.humAvg.setSmallDecimalPoint(True)
        self.humAvg.setDigitCount(4)
        self.humAvg.setProperty("intValue", 0)
        self.humAvg.setObjectName("humAvg")
        self.plotGraph = QtWidgets.QPushButton(Form)
        self.plotGraph.setGeometry(QtCore.QRect(370, 470, 141, 61))
        self.plotGraph.setObjectName("plotGraph")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(290, 250, 41, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Environment Monitor"))
        self.get_hum.setText(_translate("Form", "Get Humidity"))
        self.get_temp.setText(_translate("Form", "Get Temp"))
        self.TOR.setText(_translate("Form", "Time of Request"))
        self.exit.setText(_translate("Form", "EXIT"))
        self.threshold_button.setText(_translate("Form", "SET TEMP THRESHOLD"))
        self.degree_button.setText(_translate("Form", "°C"))
        self.fahrenheit_button.setText(_translate("Form", "°F"))
        self.refresh_checkBox.setText(_translate("Form", "Auto Refresh"))
        self.TempAndHumidity.setText(_translate("Form", "Temp and Humidity"))
        self.label.setText(_translate("Form", "Average Temperature"))
        self.label_2.setText(_translate("Form", "Average Humidity"))
        self.plotGraph.setText(_translate("Form", "Plot Graphs"))
        self.label_3.setText(_translate("Form", "%"))

